apiVersion: v1
kind: Namespace
metadata:
  name: micromart
  labels:
    name: micromart
---
apiVersion: v1
kind: Namespace
metadata:
  name: micromart-monitoring
  labels:
    name: micromart-monitoring
