apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: micromart
  labels:
    app: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: product
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: product
          image: localhost:5001/micromart-product:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
              name: grpc
            - containerPort: 8081
              name: health
            - containerPort: 9090
              name: metrics
          env:
            - name: GRPC_PORT
              value: "50051"
            - name: HTTP_PORT
              value: "8081"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-products-secret
                  key: DATABASE_URL
            - name: KAFKA_BROKERS
              value: "kafka-0.kafka:9092"
            - name: SERVICE_NAME
              value: product-service
            - name: JAEGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: observability-config
                  key: JAEGER_ENDPOINT
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: micromart
spec:
  selector:
    app: product
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product
  namespace: micromart
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
